# Zad. 


  * Proszę pobrać dane z EUROWIZJI 2014.

  * Następnie dobrać najleprzy model hierarchiczny.
  
  * Z jakimi Państwami w grupie wylądowała POLSKA?

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.io import loadmat

In [7]:
dane = loadmat("./eu_song_2014.mat")["x"][0][0][0]
k1 = loadmat("./eu_song_2014.mat")["x"][0][0][1][0][0]
k2 = loadmat("./eu_song_2014.mat")["x"][0][0][5]
dane = pd.DataFrame(dane,columns=k2)
dane.set_index(k1,inplace=True)

In [8]:
dane.head()

,Ukraine,Belarus,Azerbaijan,Iceland,Norway,Romania,Armenia,Montenegro,Greece,Poland,...,Slovenia,Finland,Spain,Switzerland,Hungary,Malta,Denmark,Netherlands,San Marino,United Kingdom
Albania,0,0,0,0,0,0,0,6,0,2,...,0,0,12,0,8,1,0,0,3,0
Armenia,0,8,0,0,0,0,0,12,0,7,...,0,0,2,5,0,0,1,4,3,0
Austria,5,0,0,2,1,8,12,0,0,0,...,0,4,0,3,7,0,0,10,0,0
Azerbaijan,10,7,0,0,0,6,0,0,2,4,...,0,0,0,0,8,5,0,0,3,0
Belarus,8,0,3,0,4,1,10,0,7,6,...,0,0,0,0,5,0,0,2,0,0

# Zad.

Możemy zwizualizować wynik na płaszczyźnie 

* t-SNE
* PCA